# Generated by Django 5.2.17 on 2026-09-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('legal_review', 'Legal Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('organization_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('other', 'Other')], default='pdf', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Version',
                'verbose_name_plural': 'Contract Versions',
                'db_table': 'contract_versions',
                'ordering': ['version_number'],
                'unique_together': {('contract', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clause_type', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('similarity_score', models.FloatField(default=0)),
                ('playbook_match', models.BooleanField(default=False)),
                ('deviation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contractversion')),
            ],
            options={
                'verbose_name': 'Clause',
                'verbose_name_plural': 'Clauses',
                'db_table': 'clauses',
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('parties', 'Parties'), ('effective_date', 'Effective Date'), ('expiry_date', 'Expiry Date'), ('payment_terms', 'Payment Terms'), ('termination', 'Termination'), ('liability_cap', 'Liability Cap'), ('renewal_window', 'Renewal Window'), ('notice_period', 'Notice Period'), ('obligation', 'Obligation')], max_length=100)),
                ('value', models.TextField()),
                ('confidence_score', models.FloatField(default=0)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='contracts.contractversion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracted Field',
                'verbose_name_plural': 'Extracted Fields',
                'db_table': 'extracted_fields',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('expiry', 'Expiry'), ('renewal', 'Renewal'), ('payment', 'Payment'), ('termination', 'Termination'), ('notice', 'Notice')], default='payment', max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('passed', 'Passed'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_obligations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='contracts.contract')),
            ],
            options={
                'db_table': 'obligations',
                'ordering': ['due_date'],
            },
        ),
    ]
